=== flaviol-souza/bench4q/trustie/Bench4Q/tag/Bench4Q_1.3.0/src/org/bench4Q/resources/bench4Q-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="bench4Q">
		<xs:annotation>
			<xs:documentation></xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="testName" type="xs:string" />
				<xs:element name="testDescription" type="xs:string" />
				<xs:element name="rbe" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="interval"
								type="xs:double" />
							<xs:element name="prepair"
								type="xs:integer" />
							<xs:element name="cooldown"
								type="xs:integer" />
							<xs:element name="out" type="xs:string" />
							<xs:element name="tolerance"
								type="xs:double" />
							<xs:element name="retry" type="xs:integer" />
							<xs:element name="thinktime"
								type="xs:double" />
							<xs:element name="mix">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration
											value="shopping" />
										<xs:enumeration
											value="ordering" />
										<xs:enumeration
											value="browsing" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="slow" type="xs:double"
								minOccurs="0" />
							<xs:element name="getImage"
								type="xs:boolean">
							</xs:element>
							<xs:element name="baseURL" type="xs:string" />
							<xs:element name="ebs"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="baseLoad"
											type="xs:integer" />
										<xs:element name="randomLoad"
											type="xs:integer" />
										<xs:element name="rate"
											type="xs:integer" />
										<xs:element name="triggerTime"
											type="xs:integer" />
										<xs:element name="stdyTime"
											type="xs:integer" />									
									</xs:sequence>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
						<xs:attribute name="rbetype">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="open" />
									<xs:enumeration value="closed" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== flaviol-souza/bench4q/trustie/Bench4Q/tag/Bench4Q_1.3.0/src/org/bench4Q/resources/bench4Q.xml
<?xml version="1.0" encoding="UTF-8"?>
<bench4Q xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bench4Q-schema.xsd">
  <testName>default name</testName>
  <testDescription>default description</testDescription>
  <rbe rbetype="closed">
    <interval>1</interval>
    <prepair>0</prepair>
    <cooldown>0</cooldown>
    <out>out</out>
    <tolerance>0.0</tolerance>
    <retry>3</retry>
    <thinktime>0.01</thinktime>
    <mix>shopping</mix>
    <slow>0.0</slow>
    <getImage>false</getImage>
    <baseURL>http://localhost:8080/bench4Q</baseURL>
    <ebs>
      <baseLoad>10</baseLoad>
      <randomLoad>0</randomLoad>
      <rate>0</rate>
      <triggerTime>0</triggerTime>
      <stdyTime>60</stdyTime>
    </ebs>
  </rbe>
</bench4Q>

=== flaviol-souza/bench4q/Bench4QTool/bench4Q.xml
<?xml version="1.0" encoding="UTF-8"?>
<bench4Q xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="src/org/bench4Q/resources/bench4Q-schema.xsd">
  <testName>testName</testName>
  <testDescription>testDescription</testDescription>
  <rbe rbetype="closed">
    <interval>1.0</interval>
    <prepair>0</prepair>
    <cooldown>10</cooldown>
    <out>out</out>
    <tolerance>0.0</tolerance>
    <retry>0</retry>
    <thinktime>0.01</thinktime>
    <urlConnectionTimeOut>0</urlConnectionTimeOut>
    <urlReadTimeOut>0</urlReadTimeOut>
    <mix>shopping</mix>
    <slow>1.0</slow>
    <getImage>false</getImage>
    <baseURL>http://localhost:8080/bench4Q</baseURL>
    <ebs>
      <baseLoad>100</baseLoad>
      <randomLoad>0</randomLoad>
      <rate>0</rate>
      <triggerTime>0</triggerTime>
      <stdyTime>60</stdyTime>
    </ebs>
  </rbe>
</bench4Q>

=== flaviol-souza/bench4q/trustie/Bench4Q/branches/20090924-connectionPool/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<bench4Q xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bench4Q-schema.xsd">
  <testName />
  <testDescription />
  <rbe rbetype="closed">
    <interval>1.0</interval>
    <prepair>600</prepair>
    <cooldown>300</cooldown>
    <out>out</out>
    <tolerance>1.0</tolerance>
    <retry>0</retry>
    <thinktime>1.0</thinktime>
    <urlConnectionTimeOut>0</urlConnectionTimeOut>
    <urlReadTimeOut>0</urlReadTimeOut>
    <mix>shopping</mix>
    <slow>1.0</slow>
    <getImage>true</getImage>
    <baseURL>http://localhost:8080/jaspte</baseURL>
    <ebs>
      <baseLoad>10</baseLoad>
      <randomLoad>10</randomLoad>
      <rate>0</rate>
      <triggerTime>10</triggerTime>
      <stdyTime>60</stdyTime>
    </ebs>
    <ebs>
      <baseLoad>20</baseLoad>
      <randomLoad>20</randomLoad>
      <rate>0</rate>
      <triggerTime>100</triggerTime>
      <stdyTime>60</stdyTime>
    </ebs>
  </rbe>
</bench4Q>
